@startuml uml
class FundoImobiliario {
    - nome: String
    - ticker: String
    - precoInicial: Double
    - investidorQualificado: Boolean
}
enum Segmento {
    + TIJOLO
    + PAPEL
    + FOF
    + HIBRIDO
    + DESENVOLVIMENTO
}
class Evento {
    - descricao: String
    - data: LocalDate
}

FundoImobiliario "*" --> "1" Segmento
FundoImobiliario "1" *-right-> "*" Evento

@enduml